/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
/home/yl9539/.local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/yl9539/.local/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
  warn(f"Failed to load image Python extension: {e}")
/home/yl9539/.local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/yl9539/.local/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
  warn(f"Failed to load image Python extension: {e}")
/home/yl9539/.local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/yl9539/.local/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
  warn(f"Failed to load image Python extension: {e}")
/home/yl9539/.local/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/yl9539/.local/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefIlEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEENS5_INS2_12MemoryFormatEEE
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "./tools/train.py", line 244, in <module>
  File "./tools/train.py", line 244, in <module>
  File "./tools/train.py", line 244, in <module>
  File "./tools/train.py", line 244, in <module>
    main()
  File "./tools/train.py", line 111, in main
    main()    
    main()  File "./tools/train.py", line 111, in main
main()

  File "./tools/train.py", line 111, in main
  File "./tools/train.py", line 111, in main
    cfg = Config.fromfile(args.config)
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 340, in fromfile
    cfg = Config.fromfile(args.config)
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 340, in fromfile
        cfg = Config.fromfile(args.config)cfg = Config.fromfile(args.config)

  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 340, in fromfile
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 340, in fromfile
        cfg_dict, cfg_text = Config._file2dict(filename,    cfg_dict, cfg_text = Config._file2dict(filename,
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 183, in _file2dict
cfg_dict, cfg_text = Config._file2dict(filename,
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 183, in _file2dict

  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 183, in _file2dict
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/config.py", line 183, in _file2dict
    check_file_exist(filename)
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
        check_file_exist(filename)    check_file_exist(filename)
check_file_exist(filename)
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/path.py", line 23, in check_file_exist

  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
        FileNotFoundError    raise FileNotFoundError(msg_tmpl.format(filename))raise FileNotFoundError(msg_tmpl.format(filename)): raise FileNotFoundError(msg_tmpl.format(filename))

file "/scratch/yl9539/mmdetection/configs/mmask_rcnn/mask_rcnn_r50_fpn_1x_coco_datapath.py" does not exist
FileNotFoundErrorFileNotFoundError
FileNotFoundError: : : file "/scratch/yl9539/mmdetection/configs/mmask_rcnn/mask_rcnn_r50_fpn_1x_coco_datapath.py" does not existfile "/scratch/yl9539/mmdetection/configs/mmask_rcnn/mask_rcnn_r50_fpn_1x_coco_datapath.py" does not existfile "/scratch/yl9539/mmdetection/configs/mmask_rcnn/mask_rcnn_r50_fpn_1x_coco_datapath.py" does not exist


ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1942262) of binary: /scratch/yl9539/miniconda3/envs/openmmlab/bin/python
Traceback (most recent call last):
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/scratch/yl9539/miniconda3/envs/openmmlab/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
./tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-12-16_17:29:20
  host      : gr044.hpc.nyu.edu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1942263)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2022-12-16_17:29:20
  host      : gr044.hpc.nyu.edu
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1942264)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2022-12-16_17:29:20
  host      : gr044.hpc.nyu.edu
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1942265)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-12-16_17:29:20
  host      : gr044.hpc.nyu.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1942262)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
